### DISCUSSION TITLE
How to animate tab switch

### DISCUSSION THREAD

**Discussion by piszczu4** [shadcn-ui/ui#2108] [General]
Is it possible to animate tab switching so that the content from current tab fade out and the content from new one fade in?

**Comment by tyler-audio** [comment]
did you find a solution to this?

**Reply by markosmk** [reply]
is posible with tailwindcss, add class to TabContent
```jsx
<TabsContent value="..." className="...">
     <div className="... animate-fade-left">
         ...
     </div>
</TabsContent>
```
and in your config tailwind, add extends like this:
```js

theme: {
 extends: {
    ...,
      keyframes: {
        ...
        "fade-left": {
          "0%": {
            opacity: "0",
            transform: "translateX(2rem)"
          },
          "100%": {
            opacity: "1",
            transform: "translateX(0)"
          }
        }
      },
      animation: {
        "fade-left": "fade-left 0.2s ease"
      },

```

**Reply by PratikDev** [reply]
quick solution. thanks @markosmk

**Reply by imtanvir** [reply]
Thanks a lot, @markosmk . It's working 🤝

**Reply by lordtottuu** [reply]
Thank you for this!

**Reply by SergeMezui16** [reply]
### Tailwind v4
For the guys who are looking for that using Tailwind V4.

```css
@theme {
  @keyframes fade-left {
    0% {
      opacity: 0;
      transform: translateX(2rem);
    }
    100% {
      opacity: 1;
      transform: translateX(0);
    }
  }
}

@utility animate-fade-left {
  animation: fade-left 0.2s ease;
}
```
