### DISCUSSION TITLE
Custom font?

### DISCUSSION THREAD

**Discussion by szelonkaMS** [shadcn-ui/ui#4143] [Q&A]
I'm starting a new Design System using shadcn-ui but following the current brand guidelines and I have to change default font to use Poppins

I couldn't find any documentation to do this. It is possible?

Any help is welcome. Thanks!

**Comment by guptaashwanee** [comment]
You need to install a font [Geist npm](https://www.npmjs.com/package/geist?activeTab=readme), even I believe you can install any font.

import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';

```html
<html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body>{children}</body>
</html>
```

or you can use google fonts also 

```
@import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap');

@tailwind base;
@tailwind components;
@tailwind utilities;
```

one more thing you need to extend the theme in the tailwing.config.js

```tailwind.config.js
module.exports = {
  ...
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-geist-sans)'],
        mono: ['var(--font-geist-mono)'],
        roboto: "Roboto", sans-serif;
      },
    },
  ...
  },
}
```

Then you can add classes like `font-mono` OR `font-sans` to use these font.

**Reply by szelonkaMS** [reply]
It was simpler than that. Just define a font to the body element and it's inherited by all components.

globals.css
``` css
@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

@layer base {
  @font-face {
    font-family: "Poppins";
    src: url("./assets/fonts/Poppins/Poppins-Regular.ttf");
    font-weight: normal;
    font-display: swap;
  }
  @font-face {
    font-family: "Poppins";
    src: url("./assets/fonts/Poppins/Poppins-Bold.ttf");
    font-weight: 700;
    font-display: swap;
  }
}

@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-background text-foreground font-poppins;
  }
}
```

tailwind.config.ts
``` typescript
import type { Config } from "tailwindcss";

const config = {
    ...,
    extend: {
      fontFamily: {
        poppins: ["Poppins", "sans-serif"],
      },
    ...,
    plugins: [require("tailwindcss-animate")],
} satisfies Config;

export default config;

```
