### DISCUSSION TITLE
Trying to install a component result in EACCES

### DISCUSSION THREAD

**Discussion by Caresle** [shadcn-ui/ui#4751] [Q&A]
I have a project with a postgresql db using docker, and when i'm trying to install a new component I get the error `EACCES: permission denied, scandir` because it's trying to read a volume of docker. Removing the folder solves the problem, but I don't want everytime that I want to add a new component having to delete the folder of docker, is there any solution for this problem?

## Components tested
- table
- dialog
```
pnpm - 9.4.0
node - 20.15
```

## Dockercompose
```yaml
services:
  postgres:
    image: postgres:15
    env_file:
      - .env.local
    ports:
      - 5433:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

```
## Components.json
```json
{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "default",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "tailwind.config.ts",
    "css": "src/app/globals.css",
    "baseColor": "zinc",
    "cssVariables": false,
    "prefix": ""
  },
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils"
  }
}
```
