### DISCUSSION TITLE
How to make the  column sticky in a wide table

### DISCUSSION THREAD

**Discussion by mohdhaider07** [shadcn-ui/ui#5338] [General]
I have a table with 8-10 columns, and when performing certain actions, I often need to scroll to the right to access the "Action" column. This makes the user experience less efficient. I would like to make the "Action" column sticky, so it stays visible even when scrolling horizontally. Any suggestions or solutions on how to achieve this?
![Screenshot from 2024-10-12 11-25-56](https://github.com/user-attachments/assets/31447ff7-95a1-4344-8df5-83e5d7ebb0e0)
![Screenshot from 2024-10-12 11-26-24](https://github.com/user-attachments/assets/3c47e3e2-d4a2-4cf5-bace-5450f56082be)

**Comment by suprunchuk** [comment]
hi. without the source code, it is difficult to suggest something. always try to attach the source code or a repository with the code.

**Comment by cookieMonsterDev** [comment]
Here is a code for general case: 

```html
<div class="wrapper">
  <table>
    <thead>
      <tr>
        <th></th>
        <th>column 1</th>
        <th>column 2</th>
        <!-- ... -->
      </tr>
    </thead>
    <tbody>
      <tr>
        <th>row 1</th>
        <td>scroll</td>
        <td>scroll</td>
        <!-- ... -->
      </tr>
      <!-- ... -->
    </tbody>
  </table>
</div>

```

```css
.wrapper {
  width: 320px;
  height: 200px;
  overflow: auto;
  position: relative;
}

table {
  table-layout: fixed;
}

thead,
tr>th {
  position: sticky;
  background: #fff;
}

thead {
  top: 0;
  z-index: 2;
}
tr>th {
  left: 0;
  z-index: 1;
}
thead tr>th:first-child {
  z-index: 3;
}

```

You may need to override default behavior of data-table, possibly by adding custom prop to table where can be passed function that will create component for your actions actions.
