### DISCUSSION TITLE
Using `light-dark` for colors

### DISCUSSION THREAD

**Discussion by Gravy59** [shadcn-ui/ui#6547] [Ideas]
Since [`light-dark`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark) is now baseline, it might be a good idea to use that syntax in v4 e.g.

```css
@theme {
  --color-background: light-dark(theme(colors.white), theme(colors.zinc.950));
  --color-foreground: light-dark(theme(colors.zinc.950), theme(colors.zinc.50));
}
```

This would be more concise and also allow intellisense to inform which colors on hover: `/* light-dark(theme(colors.zinc.950), theme(colors.zinc.50)) */`
