### DISCUSSION TITLE
Stone colour values for globals.css when using Tailwind 3.x

### DISCUSSION THREAD

**Discussion by michellepace** [shadcn-ui/ui#7435] [Q&A] [answered]
Hello.

I am using Tailwind 3.x and shadcn/ui with CSS Variables.

**Q1.** Am I correct that if I'm using Tailwind 3.x it is best to use HCL colours?

**Q2.** If yes, I am looking for this exact `globals.css` but with HCL not OKLCH: https://ui.shadcn.com/docs/theming#stone. Could anyone help me please?

Stone defined in `globals.css` (from link)

```css
:root {
  --radius: 0.625rem;
  --background: oklch(1 0 0);
  --foreground: oklch(0.147 0.004 49.25);
  --card: oklch(1 0 0);
  --card-foreground: oklch(0.147 0.004 49.25);
  /* Another 29 properties defined ... */
}

.dark {
  --background: oklch(0.147 0.004 49.25);
  --foreground: oklch(0.985 0.001 106.423);
  --card: oklch(0.216 0.006 56.043);
  --card-foreground: oklch(0.985 0.001 106.423);
  /* Another 29 properties defined ... */
}
```
