### ISSUE TITLE
accordion animations doesn't work.

### ISSUE THREAD

**Issue by bbarchuk** [shadcn-ui/ui#1063]
Hi, first of all great library. Im encountering an issue which doesn't applys me the accordion animations, so it looks a lil weird. I've changed the tailwind config and nothing. I can provide my code just in case it's that. 

``` javascript
<Accordion type="single" collapsible className="w-full">
      <AccordionItem value="item-1">
       <AccordionTrigger>Want to higlight specific sentiments?</AccordionTrigger>
       <AccordionContent>
        <h3 className="p-1 pb-2 text-black/90 font-bold text-md">Sentiment Analysis</h3>
        <p className="p-1 mt-1 mb-3 text-sm text-black/80">Gauge video content&apos;s emotional tone. Emphasize positive, negative, or neutral aspects in the translations for deeper insights and informed decisions.</p> 
        <Select>
          <SelectTrigger className="w-[300px] mb-4">
            <SelectValue placeholder="Enter a specific sentiment" />
          </SelectTrigger>
          <SelectContent>
            <SelectGroup>
              <SelectLabel>Sentiments</SelectLabel>
              <SelectItem value="Positive">Positive</SelectItem>
              <SelectItem value="Negative">Negative</SelectItem>
              <SelectItem value="Neutral">Neutral</SelectItem>
              <SelectItem value="Happy">Happy</SelectItem>
              <SelectItem value="Sad">Sad</SelectItem>
              <SelectItem value="Angry">Angry</SelectItem>
              <SelectItem value="Excited">Excited</SelectItem>
              <SelectItem value="Anxious">Anxious</SelectItem>
              <SelectItem value="Surprised">Surprised</SelectItem>
              <SelectItem value="Grateful">Grateful</SelectItem>
            </SelectGroup>
          </SelectContent>
        </Select>
       </AccordionContent>
      </AccordionItem>
     </Accordion>
```

And this is the accordion styles in my tailwind config.

``` js
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
```

**Comment by bbarchuk** [comment]
I solved my error by just separating all my accordions to a new component and just imported and user, hope it helps someone. Thanks

**Comment by thanhkk204** [comment]
All rights, Thanks for your contributes

**Comment by smohammadhn** [comment]
Make sure you only have one "keyframe" and one "animation" keys.
---

Hey everyone, just wanted to share my experience with you guys if ever anyone is reading this. If the animation if not working correctly make sure someone else has not mistakenly overridden it in the tailwind.config.js file.

In my case, my fellow teammate defined his keyframes and animations right below mine ...

Hope it helps

**Comment by viyic** [comment]
In case someone is looking for Tailwind 4 version, add the following to your `@theme`. Code taken directly from [Accordion example](https://ui.shadcn.com/docs/components/accordion).

```css
@theme {
    --animate-accordion-up: accordion-up var(--tw-animation-duration, var(--tw-duration, 0.2s)) var(--tw-ease, ease-out) var(--tw-animation-delay, 0s)
        var(--tw-animation-iteration-count, 1) var(--tw-animation-direction, normal) var(--tw-animation-fill-mode, none);
    --animate-accordion-down: accordion-down var(--tw-animation-duration, var(--tw-duration, 0.2s)) var(--tw-ease, ease-out)
        var(--tw-animation-delay, 0s) var(--tw-animation-iteration-count, 1) var(--tw-animation-direction, normal) var(--tw-animation-fill-mode, none);

    @keyframes accordion-down {
        0% {
            height: 0;
        }
        to {
            height: var(
                --radix-accordion-content-height,
                var(--bits-accordion-content-height, var(--reka-accordion-content-height, var(--kb-accordion-content-height, auto)))
            );
        }
    }
    @keyframes accordion-up {
        0% {
            height: var(
                --radix-accordion-content-height,
                var(--bits-accordion-content-height, var(--reka-accordion-content-height, var(--kb-accordion-content-height, auto)))
            );
        }
        to {
            height: 0;
        }
    }
}
```
