### ISSUE TITLE
Can you add animation to the Collapsible component like you to do the accordion component?

### ISSUE THREAD

**Issue by 684efs3** [shadcn-ui/ui#2053]
Can you add animation to the Collapsible component like you to do the accordion component? Thank you!

**Comment by imopbuilder** [comment]
@684efs3 

Update the files with the changes to have a animated collapsible like accordion

Api reference: https://www.radix-ui.com/primitives/docs/components/collapsible#animating-content-size

```tailwind.config.ts```
```ts
keyframes: {
	'collapsible-down': {
		from: { height: '0' },
		to: { height: 'var(--radix-collapsible-content-height)' },
	},
	'collapsible-up': {
		from: { height: 'var(--radix-collapsible-content-height)' },
		to: { height: '0' },
	},
},
animation: {
	'collapsible-down': 'collapsible-down 0.2s ease-out',
	'collapsible-up': 'collapsible-up 0.2s ease-out',
},
```

```collapsible.tsx``` - Inside the dir ```components/ui/collapsible.tsx```
```tsx
'use client';

import { cn } from '@/lib/utils/cn';
import * as CollapsiblePrimitive from '@radix-ui/react-collapsible';
import * as React from 'react';

const Collapsible = CollapsiblePrimitive.Root;

const CollapsibleTrigger = CollapsiblePrimitive.CollapsibleTrigger;

const CollapsibleContent = React.forwardRef<
	React.ElementRef<typeof CollapsiblePrimitive.CollapsibleContent>,
	React.ComponentPropsWithoutRef<typeof CollapsiblePrimitive.CollapsibleContent>
>(({ className, ...props }, ref) => (
	<CollapsiblePrimitive.CollapsibleContent
		ref={ref}
		className={cn('overflow-hidden data-[state=open]:animate-collapsible-down data-[state=closed]:animate-collapsible-up', className)}
		{...props}
	/>
));

export { Collapsible, CollapsibleContent, CollapsibleTrigger };
```

**Comment by imopbuilder** [comment]
@shadcn 

You can close this issue 🌟

**Comment by shadcn** [comment]
This issue has been automatically closed because it received no activity for a while. If you think it was closed by accident, please leave a comment. Thank you.

**Comment by sina-ss** [comment]
@shadcn why you are not adding animation to collapsible like accordion?

**Comment by LadislavBohm** [comment]
Update version for Tailwindcss 4 with option to turn off animations.

```typescript
type CollapsibleContentProps = React.ComponentProps<typeof CollapsiblePrimitive.CollapsibleContent> & {
  animate?: boolean;
};

function CollapsibleContent({ className, animate = true, ...props }: CollapsibleContentProps) {
  return (
    <CollapsiblePrimitive.CollapsibleContent
      data-slot="collapsible-content"
      className={cn(
        animate && "overflow-hidden transition-all data-[state=closed]:animate-collapsible-up data-[state=open]:animate-collapsible-down",
        className
      )}
      {...props}
    />
  );
}
```

added custom tailwind animation (in index.css or other):

```css
@theme {
  --animate-collapsible-down: collapsible-down 0.2s ease-out;
  --animate-collapsible-up: collapsible-up 0.2s ease-out;

  @keyframes collapsible-down {
    from {
      height: 0;
      opacity: 0;
    }
    to {
      height: var(--radix-collapsible-content-height);
      opacity: 1;
    }
  }

  @keyframes collapsible-up {
    from {
      height: var(--radix-collapsible-content-height);
      opacity: 1;
    }
    to {
      height: 0;
      opacity: 0;
    }
  }
}
```
