### ISSUE TITLE
Put full colors in CSS variables

### ISSUE THREAD

**Issue by multiwebinc** [shadcn-ui/ui#215]
I'm not sure if there is a reasoning behind the current way, but why do we have:

```js
module.exports = {
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--primary))",
      }
    }
  }
}
```

And then:

```css
@layer base {
  :root {
    --primary: 222.2 47.4% 11.2%;
  }
}
```

This way VSCode doesn't give you a color preview in the CSS file (probably other editors as well).

Wouldn't it be better to do:

```js
module.exports = {
  theme: {
    extend: {
      colors: {
        border: "var(--primary)",
      }
    }
  }
}
```

And then:

```css
@layer base {
  :root {
    --primary: hsl(222.2 47.4% 11.2%);
  }
}
```

That way we get a preview of the color and a color picker in VSCode like this beside `--primary`:

![image](https://user-images.githubusercontent.com/901732/233219762-2df64e7b-43e0-4020-bcd7-74d995fcaae3.png)
