### ISSUE TITLE
Force light theme on specific component

### ISSUE THREAD

**Issue by benbaessler** [shadcn-ui/ui#2814]
I'd like to always apply the light theme to a specific Dialog component in my project, even if the selected theme is dark mode. Is this somehow possible?

**Comment by dan5py** [comment]
Hi @benbaessler you can add a custom light class like this:

Update the `globals.css` file:
```css
@layer base {
  :root, .light {
  /* rest of css file */
```

And the you can use it in your components:

```tsx
<div className="light">
  Forced light mode
</div>
```

**Comment by shadcn** [comment]
This issue has been automatically closed because it received no activity for a while. If you think it was closed by accident, please leave a comment. Thank you.

**Comment by bhatvikrant** [comment]
> Hi @benbaessler you can add a custom light class like this:
> 
> Update the `globals.css` file:
> 
> ```css
> @layer base {
>   :root, .light {
>   /* rest of css file */
> ```
> 
> And then you can use it in your components:
> 
> ```tsx
> <div className="light">
>   Forced light mode
> </div>
> ```

This did not work for me

**Comment by FrancescoSaverioZuppichini** [comment]
same here!

**Comment by softmarshmallow** [comment]
Nice clean solution?

**Comment by Oddlaceguy49** [comment]
I found a workaround that is still compatible with shadcn theme generators! 

Edit your global.css file to look something like this: 
```css:global.css
/* Make dark: utilities match ancestor OR self, including .mode-dark islands */
@custom-variant dark (&:where(.dark &, &.dark, .mode-dark &, &.mode-dark));

/* Islands: make subtrees actually inherit the right base props */
.mode-light {
    color-scheme: light;
    color: var(--foreground);
    background-color: var(
        --background
    ); /* remove if you don't want a filled bg */
}
.mode-dark {
    color-scheme: dark;
    color: var(--foreground);
    background-color: var(--background);
}

/* PASTE/REPLACE WITH SHADCN THEME OUTPUT
   Keep the selector aliases exactly as they are below.
   - Replace the contents of :is(:root, .mode-light) with the generator’s :root block
   - Replace the contents of :is(.dark, .mode-dark) with the generator’s .dark block
*/

/* Light theme (global + islands) */
:is(:root, .mode-light) {
    /* Shadcn stuff */
}

/* Dark theme (global + islands) */
:is(.dark, .mode-dark) {
    /* Shadcn stuff */
}
```

You can now add the "mode-dark" class to force an element to be dark, and the "mode-light" class to force an element to be light. It even works if you nest elements with different modes inside each other!

<img width="1594" height="927" alt="Image" src="https://github.com/user-attachments/assets/f7d1beac-fb19-4bea-b9ff-e074870acf1c" />
