### ISSUE TITLE
[Bug]: DropdownMenuSubContent menu items, gets cut off out of screen on mobile

### ISSUE THREAD

**Issue by MilanObrenovic** [shadcn-ui/ui#2893]
This bug can clearly be seen even on the official shadcn website: https://ui.shadcn.com/docs/components/dropdown-menu

![image](https://github.com/shadcn-ui/ui/assets/56999235/7c092c64-5ccf-41f0-8b48-30fbba66690c)

This bug occurs only on mobile (obviously). Perhaps we need a different approach on how to display these sub menu items on mobile so they dont get cut off screen? Imagine how bad it would get if there are multiple sub menu item contents, level 3-4-5 etc. They wouldnt even be seen on the screen.

What do you think is the best way to solve this from the UI/UX POV?

**Comment by MilanObrenovic** [comment]
Bumping this thread. Any updates @shadcn ?

**Comment by shadcn** [comment]
This issue has been automatically closed because it received no activity for a while. If you think it was closed by accident, please leave a comment. Thank you.

**Comment by therealtgd** [comment]
Any updates on this issue? I've also noticed that the dropdown gets cut off vertically if it doesn't have enough space. And it doesn't have scroll enabled to handle this. It can be seen on the [official documentation site](https://ui.shadcn.com/docs/components/dropdown-menu).

<img width="1006" alt="image" src="https://github.com/user-attachments/assets/e18f81a4-fcdd-4add-97d6-c8ea7df14049">

**Comment by tinncdev** [comment]
Refer back to radix-ui disscussion

https://github.com/radix-ui/primitives/issues/1749

The [latest comment](https://github.com/radix-ui/primitives/issues/1749#issuecomment-2407815187) seem to works with a small adjustment

```css
div[data-radix-popper-content-wrapper]:has(> div[data-side='right']) {
  left: calc(
    min(
      0px,
      var(--radix-popper-available-width) +
        (-1 * var(--radix-popper-anchor-width))
    )
  ) !important;
}

div[data-radix-popper-content-wrapper]:has(> div[data-side='left']) {
  left: calc(
    max(
      0px,
      (-1 * var(--radix-popper-available-width)) +
        var(--radix-popper-anchor-width)
    )
  ) !important;
}
  ```
