### ISSUE TITLE
[bug]: Select removes scrollbar

### ISSUE THREAD

**Issue by LuziferSenpai** [shadcn-ui/ui#4227]
### Describe the bug

When using a select somewhere and the body has a scrollbar, this scrollbar gets removed as soon as the select is used.
![showcase](https://github.com/shadcn-ui/ui/assets/38015859/12ca8516-baa0-447f-b75a-78aa82cd9c66)

### Affected component/components

Select

### How to reproduce

1. Give the body a scrollbar
2. Add a Select
3. Open the Select

### System Info

```bash
Chrome
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by mustafaR35** [comment]
Hey I have a similar issue, where i cant scroll the content, any idea as to why that is ?

**Comment by spencersablan** [comment]
Hey friends 👋 

This seems to be a known feature of the Radix UI select component.  See [this comment](https://github.com/radix-ui/primitives/issues/1496#issuecomment-1172107676) from a similar issue raised for Radix UI. 

 One thing you can try is using a **popover** instead of a select! 😄

**Comment by Naitik2408** [comment]
Can you provide me exact path of the page where you find the issue.

**Comment by LuziferSenpai** [comment]
> Can you provide me exact path of the page where you find the issue.

You just add a select to any project and open it, you see your scrollbar dissappearing

**Comment by Emmanuel-Xs** [comment]
yeah am having the same issue

how to make the scrollbar visible when the shadcnui select component is clicked on

**Comment by osh6006** [comment]
I found a solution, but I don't know if it's the right way..

```css
/* global.css */
  html body[data-scroll-locked] {
    --removed-body-scroll-bar-size: 0 !important;
    margin-right: 0 !important;
  } 
```

**Comment by Pascalmh** [comment]
Depending on your layout you'll need to add additional classes from [react-remove-scroll-bar
](https://github.com/theKashey/react-remove-scroll-bar) which is used internally for the radix-ui/primitives.

I needed to add the `fullWidthClassName` to my "main div" (the first child after the router outlet).

See also: https://github.com/radix-ui/primitives/discussions/1586#discussioncomment-3302669

**Comment by Cloudyaa** [comment]
```css
/* global.css */
  html body[data-scroll-locked] {
    overflow: visible !important;
    margin-right: 0 !important;
  } 
```

This one worked for me - no layout shift and scroll still visible

**Comment by armya-z** [comment]
it doesnt fixed yet?
select is a very usefull and this bug is make the whole package useless...

**Comment by adrilasar** [comment]
For me is not removing the scrollbar but adding the margin (causing layout shift)
I fixed it with https://github.com/shadcn-ui/ui/issues/4227#issuecomment-2438290165

**Comment by HitishRaoP** [comment]
```
/* global.css */
html body[data-scroll-locked] {
	overflow-y: scroll !important;
	margin-right: 0px !important;
}
```
this worked for me instead of overflow visible

**Comment by cnelf** [comment]
```css
html {
  scrollbar-gutter: stable;
}
```

maybe it is a good solution.

**Comment by kie-kei** [comment]
in my case it solve:
```
body {
    margin-right: 0 !important;
    padding-right: 0 !important;
    overflow: visible !important;
}
```

**Comment by alex-mj-diff** [comment]
would be great to have a similar solution as the DropdownMenu component with the props ` modal={false}`

https://www.radix-ui.com/primitives/docs/components/dropdown-menu#root

**Comment by kevduc** [comment]
Adding yet another variation of the provided answers because this one was the cleanest option for me (especially not forcing any type of overflow/scroll on the body, just removing it):

```css
/* `html` is added to beat the specificity of just `body[data-scroll-locked]` */
html body[data-scroll-locked] {
  overflow: unset !important;
  margin-right: unset !important;
  --removed-body-scroll-bar-size: 0 !important; /* is this needed? */
}
```

Note that in my project I'm also using:

```css
html {
  scrollbar-gutter: stable;
}
```

**Comment by shadcn** [comment]
Hi. We're closing some old issues as outdated. If this is still relevant, leave a message, we'll reopen it. Thank you. Appreciate your contribution to the project - shadcn

**Comment by ali-emumba** [comment]
i am using the css below in my global.css file: 

`
html body.select-open[data-scroll-locked] {
  overflow-y: auto !important; 
}
`

this maintains the scrollbar when a select component opens but it also maintains the scrollbar when a drawer component open. I have a drawer appear from the right which has the scrollbar for the body also visible looking very odd. Any suggestions? Thanks

**Comment by CarlosVergikosk** [comment]
@shadcn i think this should be reopened, the component needs a modal property.

**Comment by YThinker** [comment]
Please reopen this issue, this greatly affects the development experience

**Comment by OliverChristensen93** [comment]
It really needs the modal property that other shadcn with this issue has (like the dropdown).

This:
```
html body[data-scroll-locked] {
  overflow: unset !important;
  margin-right: unset !important;
}
```
solved it for me.

**Comment by pillarcoin** [comment]
> [@shadcn](https://github.com/shadcn) i think this should be reopened, the component needs a modal property.

Agree. Since [Native Select](https://ui.shadcn.com/docs/components/native-select) was added to the component library, the behavior between `Select` and `Native Select` has been inconsistent: `Select` **hides** the scrollbar, while `Native Select` **does not**.

**Comment by AnthonyLightEFX** [comment]
This issue should possibly be re-opened as it's still problematic, although the root cause is in radix UI and it's dependencies.

The problem is that `react-remove-scrollbar` (radix UI dependency) is adding a style sheet to the header which is changing various aspects on the body, so even many of the suggestions here were not initially working.

I had to double the specificity on the CSS selectors to override the head inline style sheet and particularly for my case I had to add the padding-top back in:

```css
html[data-scroll-locked][data-scroll-locked],
body[data-scroll-locked][data-scroll-locked] {
    overflow: visible !important;
    margin-right: 0 !important;
    padding-right: 0 !important;
    --removed-body-scroll-bar-size: 0 !important;
    padding-top: calc(var(--spacing) * 10);
}

html {
    scrollbar-gutter: stable;
}
```
