### ISSUE TITLE
[bug]: Dialog and Sheet has no background

### ISSUE THREAD

**Issue by rytelk** [shadcn-ui/ui#4775]
### Describe the bug

Dialog and Sheet has no background

### Affected component/components

Sheet, Dialog

### How to reproduce

1. Create new project `npx shadcn@latest init dialog`
2. Replace `page.tsx' with the following code
`import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger, } from "@/components/ui/dialog"

export default function Home() {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <div>Open</div>
      </DialogTrigger>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Test title</DialogTitle>
          <DialogDescription>
            Test description
          </DialogDescription>
        </DialogHeader>
        <div>Test content</div>
      </DialogContent>
    </Dialog>
  )
}
`
3. Run application and open dialog
4. See the following result:
![image](https://github.com/user-attachments/assets/ddfc816c-831a-43d7-8459-45003198478c)

Temporary fix:

I modified the background class in the dialog component from bg-background to bg-[var(--background)], and this corrected the issue. It seems like the default background variable is not being applied correctly in some cases.

### System Info

```bash
Chrome, Windows
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by czrsd** [comment]
Hi there, I tried it and it works fine for me. ![image](https://github.com/user-attachments/assets/9633e88c-0277-4cee-8b3b-666255695707)
Could you maybe give more details of your configs?
Perhaps something is missing in your configuration that's necessary for shadcn UI: https://ui.shadcn.com/docs/installation/vite

**Comment by alexander-densley** [comment]
https://github.com/user-attachments/assets/ac50d10e-9b11-4479-a1ac-85320b234fcf

When I init a new shadcn project with dashboard-02 i get sheet's without a backgound. Looks like css variables are not being recognized.

**Comment by aigc-in-all** [comment]
It's just because the format of the color definition is wrong. and just delete this code in global.css:

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

/* delete start */
:root {
  --background: #ffffff;
  --foreground: #171717;
}

@media (prefers-color-scheme: dark) {
  :root {
    --background: #0a0a0a;
    --foreground: #ededed;
  }
}
/* delete end */

body {
  color: var(--foreground);
  background: var(--background);
  font-family: Arial, Helvetica, sans-serif;
}

@layer utilities {
  .text-balance {
    text-wrap: balance;
  }
}

@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 0 0% 3.9%;
...

...

```

Because in tailwind.config.ts, bg-background is defined like this:
```ts
// tailwind.config.js
module.exports = {
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))', <- rgb(var(--background))
        foreground: 'hsl(var(--foreground))', <- rgb(var(--foreground))
      },
    },
  },
}
```

rgb is correct, but hsl is wrong. Do you see the difference?
