### ISSUE TITLE
[bug]: `globals.css` contains default NextJS CSS variables that interfere with the theme

### ISSUE THREAD

**Issue by SDrinkwater** [shadcn-ui/ui#4845]
### Describe the bug

**Issue:** After running `npx shadcn@latest init -d`, the resulting `globals.css` contains both the default NextJS setup as well as the themed css variables. These variables overlap and cause issues with the tailwind setup created via the shadcn command.

As a concrete example, the `tailwind.config.ts` background looks like this: `background: "hsl(var(--background))"` (note that it expects `--background` to be a hsl value. The problem is that the default NextJS setup uses hex for the themed colors. These override the ones specified by the shadcn theme and effectively corrupt the theme. The resulting style given to the browser looks like:
```css
.bg-background {
    background-color: hsl(#ffffff);
}
```

Note that it is trying to use a hex value as an hsl value.

Since the value passed to the browser is not valid, it renders the background color as transparent which messes with all of the components that rely on this background theming (read: practically all of them).

I noticed this initially on the slider component as the thumb was entirely transparent.

**Expected:** The resulting `globals.css` file should not contain the default NextJS setup.

**Workaround:** If others face this issue and notice that their components look a little funny, simply remove the default NextJS theming (first `:root` block through to the first `@layer utilities` block

See the first part of the resulting `globals.css` file below:

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --background: #ffffff;
  --foreground: #171717;
}

@media (prefers-color-scheme: dark) {
  :root {
    --background: #0a0a0a;
    --foreground: #ededed;
  }
}

body {
  color: var(--foreground);
  background: var(--background);
  font-family: Arial, Helvetica, sans-serif;
}

@layer utilities {
  .text-balance {
    text-wrap: balance;
  }
}


@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 0 0% 3.9%;
    
...
```

### Affected component/components

All

### How to reproduce

1. Run `npx shadcn@latest init -d`
2. Install slider `npx shadcn@latest add slider`
3. Add slider to component and observe transparent slider thumb.

### System Info

```bash
Shadcn: 2.0.6
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
