### ISSUE TITLE
fontFamily is not applied in tailwind.config.js file

### ISSUE THREAD

**Issue by lightbluepoppy** [shadcn-ui/ui#516]
When I comment out the code below from `tailwindcss.config.cjs` file, I get sans-fonts displayed. Otherwise I get serif-fonts with the `sans` key somehow. How to get proper fonts?

```css
fontFamily: {
    sans: ['var(--font-sans)', ...fontFamily.sans],
},
```
