### ISSUE TITLE
[bug]: Add webkit optimizations to global CSS configuration

### ISSUE THREAD

**Issue by Abdel-Monaam-Aouini** [shadcn-ui/ui#5626]
## Overview
The current global CSS configuration would benefit from additional webkit-specific optimizations to enhance cross-browser compatibility, mobile device support, and overall rendering quality.

## Suggested Changes
Add the following webkit and cross-browser optimizations to the base layer of the global CSS configuration:

```css
@layer base {
  * {
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    text-rendering: optimizeLegibility;
    -webkit-tap-highlight-color: transparent;
  }
  
  body {
    -webkit-overflow-scrolling: touch;
    text-size-adjust: 100%;
    -webkit-text-size-adjust: 100%;
  }
  
  input, textarea, button {
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
  }
}
```

## Benefits
1. **Improved Text Rendering**
   - Better font smoothing across browsers
   - Optimized legibility for all text elements

2. **Enhanced Mobile Experience**
   - Proper text sizing on mobile devices
   - Improved touch scrolling behavior
   - Removed default tap highlights
   - Better form element appearance on iOS

3. **Better Cross-Browser Consistency**
   - Normalized appearance across different browsers
   - Consistent form element styling

## Implementation
This can be added to the existing `globals.css` template that's generated when initializing a new project. These changes are purely additive and won't affect existing functionality.

## Additional Context
These optimizations are commonly used in production applications and follow best practices for cross-browser compatibility. They address common issues with text rendering and mobile device interactions.

## Related Resources
- [Apple's -webkit-font-smoothing documentation](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariCSSRef/Articles/StandardCSSProperties.html#//apple_ref/doc/uid/TP30001266-_webkit_font_smoothing)
- [MDN text-rendering documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/text-rendering)

### Affected component/components

config

### How to reproduce

:)

### System Info

```bash
mobile
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
