### ISSUE TITLE
[bug]: DarkMode is not working in RemixV2

### ISSUE THREAD

**Issue by sbeckerdev** [shadcn-ui/ui#5917]
### Describe the bug

The instructions of Darkmode for Remix, it doesn’t work with the structure of the last version. The theme is not applied to the class using the toggle. 

### Affected component/components

All

### How to reproduce

Follow the steps for Darkmode. They are not the same as the root in the last version.

### System Info

```bash
Local storage not working
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by lfgtavora** [comment]
not working on nextjs15 too

**Comment by yigsvnsla** [comment]
verify that you are using the useTheme() function of remix and not the one of next

**Comment by MojaveHao** [comment]
I'm definitely using the `useTheme` provided by remix-themes, and I'm sure everyone else should too.

**Comment by MojaveHao** [comment]
> 我肯定会使用 remix-themes 提供的 `useTheme` ，我相信其他人也应该这样做。

```css
:root[class~='dark'] {
    --background: 240 10% 3.9%;
    --foreground: 0 0% 98%;
    --card: 240 10% 3.9%;
    --card-foreground: 0 0% 98%;
    --popover: 240 10% 3.9%;
    --popover-foreground: 0 0% 98%;
    --primary: 0 0% 98%;
    --primary-foreground: 240 5.9% 10%;
    --secondary: 240 3.7% 15.9%;
    --secondary-foreground: 0 0% 98%;
    --muted: 240 3.7% 15.9%;
    --muted-foreground: 240 5% 64.9%;
    --accent: 240 3.7% 15.9%;
    --accent-foreground: 0 0% 98%;
    --destructive: 0 62.8% 30.6%;
    --destructive-foreground: 0 0% 98%;
    --border: 240 3.7% 15.9%;
    --input: 240 3.7% 15.9%;
    --ring: 240 4.9% 83.9%;
    --chart-1: 220 70% 50%;
    --chart-2: 160 60% 45%;
    --chart-3: 30 80% 55%;
    --chart-4: 280 65% 60%;
    --chart-5: 340 75% 55%;
    --sidebar-background: 240 5.9% 10%;
    --sidebar-foreground: 240 4.8% 95.9%;
    --sidebar-primary: 224.3 76.3% 48%;
    --sidebar-primary-foreground: 0 0% 100%;
    --sidebar-accent: 240 3.7% 15.9%;
    --sidebar-accent-foreground: 240 4.8% 95.9%;
    --sidebar-border: 240 3.7% 15.9%;
    --sidebar-ring: 217.2 91.2% 59.8%;
  }
```
I added this bunch of stuff to my tailwind.css, and my problems magically disappeared. We should all try copying something from our own `:dark` to `:root[class~='dark']`.
