### ISSUE TITLE
[bug]: SIderbar turn transparent on mobile

### ISSUE THREAD

**Issue by sahilofficial97** [shadcn-ui/ui#6002]
### Describe the bug

When i open the sidebar on mobile i can see the calender but the background is transparent. I'm also getting a warning message: "@radix-ui_react-dialog.js?v=452130b3:336 Warning: Missing `Description` or `aria-describedby={undefined}` for {DialogContent}."

### Affected component/components

Sidebar

### How to reproduce

Open Sidebar on mobile
<img width="477" alt="Screen Shot 2024-12-05 at 11 53 05 PM" src="https://github.com/user-attachments/assets/1db323e3-2305-42b3-bbfb-df568b559a4a">

### Logs

```bash
Warning: Missing `Description` or `aria-describedby={undefined}` for {DialogContent}.
```

### System Info

```bash
Chrome,Mac
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by ashish-maurya531** [comment]
@sahilofficial97 can you provide more details about how to reproduce the same

**Comment by ajaysehwal** [comment]
add this code in your global.css file  
`@layer base {
  :root {
    --sidebar-background: 0 0% 98%;
    --sidebar-foreground: 240 5.3% 26.1%;
    --sidebar-primary: 240 5.9% 10%;
    --sidebar-primary-foreground: 0 0% 98%;
    --sidebar-accent: 240 4.8% 95.9%;
    --sidebar-accent-foreground: 240 5.9% 10%;
    --sidebar-border: 220 13% 91%;
    --sidebar-ring: 217.2 91.2% 59.8%;
  }

  .dark {
    --sidebar-background: 240 5.9% 10%;
    --sidebar-foreground: 240 4.8% 95.9%;
    --sidebar-primary: 224.3 76.3% 48%;
    --sidebar-primary-foreground: 0 0% 100%;
    --sidebar-accent: 240 3.7% 15.9%;
    --sidebar-accent-foreground: 240 4.8% 95.9%;
    --sidebar-border: 240 3.7% 15.9%;
    --sidebar-ring: 217.2 91.2% 59.8%;
  }
}
`

**Comment by jansedlon** [comment]
@ajaysehwal This EXACT issue happened to me yesterday as well and the cause was that i edited `sidebar-background` color and i had `%` after the first hsl value so like `0% 100% 100%`

**Comment by TahirAlauddin** [comment]
![image](https://github.com/user-attachments/assets/9a0b425c-2ad8-4bbe-91fb-3c3b529fc13b)

Got a similar problem. It was also giving an error: 

```
DialogContent requires a DialogTitle for the component to be accessible for screen reader users.

If you want to hide the DialogTitle, you can wrap it with our VisuallyHidden component.

For more information, see https://radix-ui.com/primitives/docs/components/dialog
```

**Comment by olivermontes** [comment]
> 
> Got a similar problem. It was also giving an error:
> 
> ```
> DialogContent requires a DialogTitle for the component to be accessible for screen reader users.
> 
> If you want to hide the DialogTitle, you can wrap it with our VisuallyHidden component.
> 
> For more information, see https://radix-ui.com/primitives/docs/components/dialog
> ```

@TahirAlauddin  Same here, only need add few lines

![Screenshot 2024-12-12 at 19 36 50](https://github.com/user-attachments/assets/db60ef95-0d97-40b6-83e9-6a85e7ba1245)

**Comment by bennietokyotechies** [comment]
Replace the `bg-sidebar` by `bg-accent` resolves this issue in my setup.
![image](https://github.com/user-attachments/assets/815db7bc-e685-448e-bc69-4f56cc3f0d14)
<img width="493" alt="image" src="https://github.com/user-attachments/assets/b026665f-ed99-4760-b7ee-13434b90aaad" />

**Comment by ovxdev0** [comment]
In my case adding `--sidebar-background` in `global.css` fixed the issue.

```css
@layer base {
    :root {
        --background: 0 0% 100%;
        --foreground: 224 71.4% 4.1%;
        --card: 0 0% 100%;
        --card-foreground: 224 71.4% 4.1%;
        --popover: 0 0% 100%;
        --popover-foreground: 224 71.4% 4.1%;
        --primary: 262.1 83.3% 57.8%;
        --primary-foreground: 210 20% 98%;
        --secondary: 220 14.3% 95.9%;
        --secondary-foreground: 220.9 39.3% 11%;
        --muted: 220 14.3% 95.9%;
        --muted-foreground: 220 8.9% 46.1%;
        --accent: 220 14.3% 95.9%;
        --accent-foreground: 220.9 39.3% 11%;
        --destructive: 0 84.2% 60.2%;
        --destructive-foreground: 210 20% 98%;
        --border: 220 13% 91%;
        --input: 220 13% 91%;
        --ring: 262.1 83.3% 57.8%;
        --radius: 0.5rem;
        --chart-1: 12 76% 61%;
        --chart-2: 173 58% 39%;
        --chart-3: 197 37% 24%;
        --chart-4: 43 74% 66%;
        --chart-5: 27 87% 67%;
       /* sidebar bg variable */
        --sidebar-background: 0 0% 100%;
    }

    .dark {
        --background: 224 71.4% 4.1%;
        --foreground: 210 20% 98%;
        --card: 224 71.4% 4.1%;
        --card-foreground: 210 20% 98%;
        --popover: 224 71.4% 4.1%;
        --popover-foreground: 210 20% 98%;
        --primary: 263.4 70% 50.4%;
        --primary-foreground: 210 20% 98%;
        --secondary: 215 27.9% 16.9%;
        --secondary-foreground: 210 20% 98%;
        --muted: 215 27.9% 16.9%;
        --muted-foreground: 217.9 10.6% 64.9%;
        --accent: 215 27.9% 16.9%;
        --accent-foreground: 210 20% 98%;
        --destructive: 0 62.8% 30.6%;
        --destructive-foreground: 210 20% 98%;
        --border: 215 27.9% 16.9%;
        --input: 215 27.9% 16.9%;
        --ring: 263.4 70% 50.4%;
        --chart-1: 220 70% 50%;
        --chart-2: 160 60% 45%;
        --chart-3: 30 80% 55%;
        --chart-4: 280 65% 60%;
        --chart-5: 340 75% 55%;
        /* sidebar bg variable */
        --sidebar-background: 215 27.9% 16.9%;
    }
}
```

**Comment by hunter-nl** [comment]
I got the same issue. Replacing the bg-sidebar by bg-accent solve it for now. 
In tailwindcss 4 --sidebar-background does not exist in the default color themes https://ui.shadcn.com/docs/theming#base-colors.
Even If I add it, then this will not being applied. Can this fixed?
shadcn version: 2.4.0-canary.17

**Comment by Mohamedkrms** [comment]
there are problem in shadcn new version

**Comment by btnalexandre** [comment]
Indeed var --sidebar-background is missing in documentation : https://ui.shadcn.com/docs/theming

**Comment by btnalexandre** [comment]
I added this to my globals.css and it worked. I just based `--sidebar-background` on the existing `--sidebar` variable.

```css
:root {
  --sidebar-background: oklch(0.985 0 0);
}
```

```css
.dark {
  --sidebar-background: oklch(0.205 0 0);
}
```
