### ISSUE TITLE
[bug]: Build Error With Tailwind CSS Prefix `The 'border-border' class does not exist.`

### ISSUE THREAD

**Issue by YTKme** [shadcn-ui/ui#6066]
### Describe the bug

When working with a Next.js project using Tailwind CSS with a Prefix such as `tw-`, the project got Build Error below. It seem like there was a [PR 770](https://github.com/shadcn-ui/ui/pull/770) trying to fix this issue, but I am getting this error on a project I am working on, as well as from a newly created project for testing.

I read [someone noted on the PR](https://github.com/shadcn-ui/ui/pull/770#pullrequestreview-1506748574) that classes applied in the CSS is missing the prefix, and [someone updated stating fix was added to latest commit](https://github.com/shadcn-ui/ui/pull/770#issuecomment-1614471624), but I am still encountering this issue.

```
Error evaluating Node.js code
CssSyntaxError: /Users/yk/Desktop/Project/Repository/YK/T/napp/app/globals.css:1:1: The `border-border` class does not exist. If `border-border` is a custom class, make sure it is defined within a `@layer` directive.
```

<img width="971" alt="image" src="https://github.com/user-attachments/assets/432d5f59-79af-4452-b5ae-ecbf19898a0c" />

### Affected component/components

All

### How to reproduce

1. Create a Next.js application using `npx create-next-app@latest`
2. Navigate to the new application directory, update the project with `npx shadcn@latest init -d`
3. Update `tailwind.config.ts` with `prefix: "tw-",` under `export default` configuration
4. Update `components.json` configuration with `"prefix": "tw-"`

> Note: I tried with updating `tailwind.config.ts` first then running `npx shadcn@latest init -d`, but same result.

### Codesandbox/StackBlitz link

https://stackblitz.com/edit/stackblitz-starters-g75bc5hq?file=tailwind.config.ts,components.json

### Logs

```bash
Error evaluating Node.js code
CssSyntaxError: /Users/yk/Desktop/Project/Repository/YK/T/napp/app/globals.css:1:1: The `border-border` class does not exist. If `border-border` is a custom class, make sure it is defined within a `@layer` directive.
    [at Input.error (turbopack://[project]/node_modules/postcss/lib/input.js:106:16)]
    [at AtRule.error (turbopack://[project]/node_modules/postcss/lib/node.js:145:32)]
    [at processApply (/Users/yk/Desktop/Project/Repository/YK/T/napp/node_modules/tailwindcss/lib/lib/expandApplyAtRules.js:380:29)]
    [at /Users/yk/Desktop/Project/Repository/YK/T/napp/node_modules/tailwindcss/lib/lib/expandApplyAtRules.js:551:9]
    [at /Users/yk/Desktop/Project/Repository/YK/T/napp/node_modules/tailwindcss/lib/processTailwindFeatures.js:55:50]
    [at async plugins (/Users/yk/Desktop/Project/Repository/YK/T/napp/node_modules/tailwindcss/lib/plugin.js:38:17)]
    [at async LazyResult.runAsync (turbopack://[project]/node_modules/postcss/lib/lazy-result.js:261:11)]
    [at async transform (turbopack://[project]/postcss.config.mjs/transform.ts:79:34)]
    [at async run (turbopack://[turbopack-node]/ipc/evaluate.ts:92:23)]
```

### System Info

```bash
System:
- macOS Sequoia 15.2 (24C101)
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by yourcasualdev** [comment]
I am having exact issue out of nowhere.

**Comment by njacob1001** [comment]
Same issue border-border doesn't exist and bg-background

**Comment by bangonkali** [comment]
Is this not because of tailwind 4 recently dropping?

**Comment by IrakliK** [comment]
Running into the same issue

**Comment by njacob1001** [comment]
Hi guys, this is probably because you are using `shadcn/ui` config, which are adding extra variables using v3 configuration file.

There is two ways to fix this issue so far, the first one is already in the tailwind documentation (I didn't test it but it makes sense):
[Using a JavaScript config file](https://tailwindcss.com/docs/upgrade-guide#using-a-javascript-config-file)

```css
@config "../../tailwind.config.js";
```

there is other alternative I tried and it works for me and it was about transorm all extended theme colors from the JS configuration files in CSS variables just like this:

```css
@import "tailwindcss";
@variant dark (&:where(.dark, .dark *));
@theme {
  --color-background: light-dark(oklch(100% 0 106.37), oklch(13.71% 0.036 258.53));
  --color-foreground: light-dark(oklch(23.76% 0 0), oklch(91.57% 0 0));
  --color-card: light-dark(oklch(100% 0 106.37), oklch(13.71% 0.036 258.53));
  --color-card-foreground: light-dark(oklch(13.71% 0.036 258.53), oklch(98.38% 0.0035 247.86));
  --color-popover: light-dark(oklch(100% 0 106.37), oklch(13.71% 0.036 258.53));
  --color-popover-foreground: light-dark(oklch(13.71% 0.036 258.53), oklch(98.38% 0.0035 247.86));
  --color-primary: light-dark(oklch(20.79% 0.0399 265.73), oklch(98.38% 0.0035 247.86));
  --color-primary-foreground: light-dark(oklch(98.38% 0.0035 247.86), oklch(20.79% 0.0399 265.73));
  --color-secondary: light-dark(oklch(96.84% 0.0068 247.9), oklch(28% 0.0369 259.97));
  --color-secondary-foreground: light-dark(oklch(20.79% 0.0399 265.73), oklch(98.38% 0.0035 247.86));
  --color-muted: light-dark(oklch(96.76% 0.0013 286.38), oklch(28% 0.0369 259.97));
  --color-muted-foreground: light-dark(oklch(55.19% 0.0137 285.94), oklch(71.07% 0.0351 256.79));
  --color-accent:light-dark(oklch(96.84% 0.0068 247.9), oklch(28% 0.0369 259.97));
  --color-accent-foreground: light-dark(oklch(20.79% 0.0399 265.73), oklch(98.38% 0.0035 247.86));
  --color-destructive: light-dark(oklch(63.68% 0.2078 25.33), oklch(39.59% 0.1331 25.72));
  --color-destructive-foreground: light-dark(oklch(98.38% 0.0035 247.86), oklch(98.38% 0.0034 247.86));
  --color-border: light-dark(oklch(93.06% 0.0125 38.2), oklch(28% 0.0369 259.97));
  --color-input: light-dark(oklch(92.9% 0.0126 255.53), oklch(28% 0.0369 259.97));
  --color-ring: light-dark(oklch(13.71% 0.036 258.53), oklch(86.88% 0.0198 252.85));
  --color-sidebar-background: light-dark(oklch(98.23% 0.0052 258.33), oklch(22.67% 0 0));
  --color-sidebar-foreground: light-dark(oklch(37.05% 0.012 285.8), oklch(96.76% 0.0013 286.38));
  --color-sidebar-primary: light-dark(oklch(21.03% 0.0059 285.88), oklch(48.78% 0.217 264.39));
  --color-sidebar-primary-foreground: light-dark(oklch(98.48% 0 0), oklch(100% 0 106.37));
  --color-sidebar-accent: light-dark(oklch(96.76% 0.0013 286.38), oklch(27.41% 0.0055 286.03));
  --color-sidebar-accent-foreground: light-dark(oklch(21.03% 0.0059 285.88), oklch(96.76% 0.0013 286.38));
  --color-sidebar-border: light-dark(oklch(92.78% 0.0058 264.53), oklch(27.41% 0.0055 286.03));
  --color-sidebar-ring: light-dark(oklch(62.32% 0.1879 259.8), oklch(62.32% 0.1879 259.8));

  --radius: 0.5rem;

  --radius-lg: var(--radius);
  --radius-md: calc(var(--radius) - 2px);
  --radius-sm: calc(var(--radius) - 4px);

  --animate-accordion-down: ccordion-down 0.2s ease-out;
  --animate-accordion-up: accordion-up 0.2s ease-out;

  @keyframes accordion-down {
    from { height: 0 }
    to { height: var(--radix-accordion-content-height, 0) }
  }

  @keyframes accordion-up {
    from {
      height: var(--radix-accordion-content-height, 0)
    }
    to {
      height: 0
    }
  }
}
```

so now you will not use `@apply` approach for colors, you can use the CSS variables for that.

```
@layer base {
  * {
    border-color: var(--color-border); /* @apply border-border; */
  }
  body {
    @apply font-sans antialiased;
    /* @apply bg-background text-foreground; */
    background-color: var(--color-background);
    color: var(--color-foreground);
  }
}
```

**Comment by kurkomisi** [comment]
I have a slightly different setup, but maybe it is related.

I installed `shadcn/ui` manually using the copy-paste method, but when I ran

`yarn dlx @tailwindcss/cli -i ./input.css -o ./output.css`

I encountered the following errors:

```
Error: Cannot apply unknown utility class: border-border  
Error: Cannot apply unknown utility class: bg-background  
Error: Cannot apply unknown utility class: text-foreground 
```

Additionally, `bg-border` for the `Separator` component did not load. After further investigation, this issue affects all `bg-*` and `text-*` prefixed classes.

**Setup**

* `tailwindcss@4.0.1`
* `@tailwindcss/cli@4.0.1`

I spent half a day debugging and the best solution I could come up with was defining functional utilities and themes for these class groups.

The following `globals.css` file resolved the issue:

```
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
    :root {
        --background: 0 0% 100%;
        --foreground: 222.2 47.4% 11.2%;
        --muted: 210 40% 96.1%;
        --muted-foreground: 215.4 16.3% 46.9%;
        --popover: 0 0% 100%;
        --popover-foreground: 222.2 47.4% 11.2%;
        --border: 214.3 31.8% 91.4%;
        --input: 214.3 31.8% 91.4%;
        --card: 0 0% 100%;
        --card-foreground: 222.2 47.4% 11.2%;
        --primary: 222.2 47.4% 11.2%;
        --primary-foreground: 210 40% 98%;
        --secondary: 210 40% 96.1%;
        --secondary-foreground: 222.2 47.4% 11.2%;
        --accent: 210 40% 96.1%;
        --accent-foreground: 222.2 47.4% 11.2%;
        --destructive: 0 100% 50%;
        --destructive-foreground: 210 40% 98%;
        --ring: 215 20.2% 65.1%;
        --radius: 0.5rem;
    }

    .dark {
        --background: 224 71% 4%;
        --foreground: 213 31% 91%;
        --muted: 223 47% 11%;
        --muted-foreground: 215.4 16.3% 56.9%;
        --accent: 216 34% 17%;
        --accent-foreground: 210 40% 98%;
        --popover: 224 71% 4%;
        --popover-foreground: 215 20.2% 65.1%;
        --border: 216 34% 17%;
        --input: 216 34% 17%;
        --card: 224 71% 4%;
        --card-foreground: 213 31% 91%;
        --primary: 210 40% 98%;
        --primary-foreground: 222.2 47.4% 1.2%;
        --secondary: 222.2 47.4% 11.2%;
        --secondary-foreground: 210 40% 98%;
        --destructive: 0 63% 31%;
        --destructive-foreground: 210 40% 98%;
        --ring: 216 34% 17%;
    }
}

/* -----------------------------------------  Fix for missing utilities  ----------------------------------------- */

@utility border-border {
    border-color: hsl(var(--border));
}

@theme {
    --bg-background: hsl(var(--background));
    --bg-foreground: hsl(var(--foreground));
    --bg-muted: hsl(var(--muted));
    --bg-muted-foreground: hsl(var(--muted-foreground));
    --bg-popover: hsl(var(--popover));
    --bg-popover-foreground: hsl(var(--popover-foreground));
    --bg-border: hsl(var(--border));
    --bg-input: hsl(var(--input));
    --bg-card: hsl(var(--card));
    --bg-card-foreground: hsl(var(--card-foreground));
    --bg-primary: hsl(var(--primary));
    --bg-primary-foreground: hsl(var(--primary-foreground));
    --bg-secondary: hsl(var(--secondary));
    --bg-secondary-foreground: hsl(var(--secondary-foreground));
    --bg-accent: hsl(var(--accent));
    --bg-accent-foreground: hsl(var(--accent-foreground));
    --bg-destructive: hsl(var(--destructive));
    --bg-destructive-foreground: hsl(var(--destructive-foreground));
    --bg-ring: hsl(var(--ring));
}

@utility bg-* {
    background-color: --value(--bg-*);
}

@theme {
    --text-background: hsl(var(--background));
    --text-foreground: hsl(var(--foreground));
    --text-muted: hsl(var(--muted));
    --text-muted-foreground: hsl(var(--muted-foreground));
    --text-popover: hsl(var(--popover));
    --text-popover-foreground: hsl(var(--popover-foreground));
    --text-border: hsl(var(--border));
    --text-input: hsl(var(--input));
    --text-card: hsl(var(--card));
    --text-card-foreground: hsl(var(--card-foreground));
    --text-primary: hsl(var(--primary));
    --text-primary-foreground: hsl(var(--primary-foreground));
    --text-secondary: hsl(var(--secondary));
    --text-secondary-foreground: hsl(var(--secondary-foreground));
    --text-accent: hsl(var(--accent));
    --text-accent-foreground: hsl(var(--accent-foreground));
    --text-destructive: hsl(var(--destructive));
    --text-destructive-foreground: hsl(var(--destructive-foreground));
    --text-ring: hsl(var(--ring));
}

@utility text-* {
    color: --value(--text-*);
}

/* ------------------------------------------------------------------------------------------------------------------- */

@layer base {
    * {
        @apply border-border;
    }
    body {
        @apply font-sans antialiased bg-background text-foreground;
    }
}
```

**Comment by lutzseverino** [comment]
This is also happening in v3. I think this is pretty urgent, following the docs causes this on every setup with Vite, even if you downgrade to TailwindCSS v3.

**Comment by YTKme** [comment]
I tried this out on `tailwindcss` version 4, but still doesn't seem to like the `prefix`. Getting an error for `border-border`.

```
Error: Cannot apply unknown utility class: border-border
```

<img width="979" alt="Image" src="https://github.com/user-attachments/assets/c7d6d199-6518-4ac2-a41a-0402da750b40" />

`components.json`

```json
{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "new-york",
  "rsc": false,
  "tsx": true,
  "tailwind": {
    "config": "tailwind.config.js",
    "css": "app/global.css",
    "baseColor": "zinc",
    "cssVariables": true,
    "prefix": "tw"
  },
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils",
    "ui": "@/components/ui",
    "lib": "@/lib",
    "hooks": "@/hooks"
  },
  "iconLibrary": "lucide"
}
```

`global.css`

```css
/* @import "tailwindcss"; */
@import "tailwindcss" prefix(tw);

@plugin "tailwindcss-animate";

@plugin 'tailwindcss-animate';

@custom-variant dark (&:is(.dark *));

@theme {
  --color-background: hsl(var(--background));
  --color-foreground: hsl(var(--foreground));

  --color-card: hsl(var(--card));
  --color-card-foreground: hsl(var(--card-foreground));

  --color-popover: hsl(var(--popover));
  --color-popover-foreground: hsl(var(--popover-foreground));

  --color-primary: hsl(var(--primary));
  --color-primary-foreground: hsl(var(--primary-foreground));

  --color-secondary: hsl(var(--secondary));
  --color-secondary-foreground: hsl(var(--secondary-foreground));

  --color-muted: hsl(var(--muted));
  --color-muted-foreground: hsl(var(--muted-foreground));

  --color-accent: hsl(var(--accent));
  --color-accent-foreground: hsl(var(--accent-foreground));

  --color-destructive: hsl(var(--destructive));
  --color-destructive-foreground: hsl(var(--destructive-foreground));

  --color-border: hsl(var(--border));
  --color-input: hsl(var(--input));
  --color-ring: hsl(var(--ring));

  --color-chart-1: hsl(var(--chart-1));
  --color-chart-2: hsl(var(--chart-2));
  --color-chart-3: hsl(var(--chart-3));
  --color-chart-4: hsl(var(--chart-4));
  --color-chart-5: hsl(var(--chart-5));

  --color-sidebar: hsl(var(--sidebar-background));
  --color-sidebar-foreground: hsl(var(--sidebar-foreground));
  --color-sidebar-primary: hsl(var(--sidebar-primary));
  --color-sidebar-primary-foreground: hsl(var(--sidebar-primary-foreground));
  --color-sidebar-accent: hsl(var(--sidebar-accent));
  --color-sidebar-accent-foreground: hsl(var(--sidebar-accent-foreground));
  --color-sidebar-border: hsl(var(--sidebar-border));
  --color-sidebar-ring: hsl(var(--sidebar-ring));

  --radius-lg: var(--radius);
  --radius-md: calc(var(--radius) - 2px);
  --radius-sm: calc(var(--radius) - 4px);

  --animate-accordion-down: accordion-down 0.2s ease-out;
  --animate-accordion-up: accordion-up 0.2s ease-out;

  @keyframes accordion-down {
    from {
      height: 0;
    }
    to {
      height: var(--radix-accordion-content-height);
    }
  }
  @keyframes accordion-up {
    from {
      height: var(--radix-accordion-content-height);
    }
    to {
      height: 0;
    }
  }
}

/*
  The default border color has changed to `currentColor` in Tailwind CSS v4,
  so we've added these compatibility styles to make sure everything still
  looks the same as it did with Tailwind CSS v3.

  If we ever want to remove these styles, we need to add an explicit border
  color utility to any element that depends on these defaults.
*/
@layer base {
  *,
  ::after,
  ::before,
  ::backdrop,
  ::file-selector-button {
    border-color: var(--color-gray-200, currentColor);
  }
}

@layer utilities {
  body {
    font-family: Arial, Helvetica, sans-serif;
  }
}

@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 0 0% 3.9%;
    --card: 0 0% 100%;
    --card-foreground: 0 0% 3.9%;
    --popover: 0 0% 100%;
    --popover-foreground: 0 0% 3.9%;
    --primary: 0 0% 9%;
    --primary-foreground: 0 0% 98%;
    --secondary: 0 0% 96.1%;
    --secondary-foreground: 0 0% 9%;
    --muted: 0 0% 96.1%;
    --muted-foreground: 0 0% 45.1%;
    --accent: 0 0% 96.1%;
    --accent-foreground: 0 0% 9%;
    --destructive: 0 84.2% 60.2%;
    --destructive-foreground: 0 0% 98%;
    --border: 0 0% 89.8%;
    --input: 0 0% 89.8%;
    --ring: 0 0% 3.9%;
    --chart-1: 12 76% 61%;
    --chart-2: 173 58% 39%;
    --chart-3: 197 37% 24%;
    --chart-4: 43 74% 66%;
    --chart-5: 27 87% 67%;
    --radius: 0.5rem;
    --sidebar-background: 0 0% 98%;
    --sidebar-foreground: 240 5.3% 26.1%;
    --sidebar-primary: 240 5.9% 10%;
    --sidebar-primary-foreground: 0 0% 98%;
    --sidebar-accent: 240 4.8% 95.9%;
    --sidebar-accent-foreground: 240 5.9% 10%;
    --sidebar-border: 220 13% 91%;
    --sidebar-ring: 217.2 91.2% 59.8%;
  }
  .dark {
    --background: 0 0% 3.9%;
    --foreground: 0 0% 98%;
    --card: 0 0% 3.9%;
    --card-foreground: 0 0% 98%;
    --popover: 0 0% 3.9%;
    --popover-foreground: 0 0% 98%;
    --primary: 0 0% 98%;
    --primary-foreground: 0 0% 9%;
    --secondary: 0 0% 14.9%;
    --secondary-foreground: 0 0% 98%;
    --muted: 0 0% 14.9%;
    --muted-foreground: 0 0% 63.9%;
    --accent: 0 0% 14.9%;
    --accent-foreground: 0 0% 98%;
    --destructive: 0 62.8% 30.6%;
    --destructive-foreground: 0 0% 98%;
    --border: 0 0% 14.9%;
    --input: 0 0% 14.9%;
    --ring: 0 0% 83.1%;
    --chart-1: 220 70% 50%;
    --chart-2: 160 60% 45%;
    --chart-3: 30 80% 55%;
    --chart-4: 280 65% 60%;
    --chart-5: 340 75% 55%;
    --sidebar-background: 240 5.9% 10%;
    --sidebar-foreground: 240 4.8% 95.9%;
    --sidebar-primary: 224.3 76.3% 48%;
    --sidebar-primary-foreground: 0 0% 100%;
    --sidebar-accent: 240 3.7% 15.9%;
    --sidebar-accent-foreground: 240 4.8% 95.9%;
    --sidebar-border: 240 3.7% 15.9%;
    --sidebar-ring: 217.2 91.2% 59.8%;
  }
}

@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-background text-foreground;
  }
}
```
