### ISSUE TITLE
[bug]: The new theme changes almost broke all of my custom styling

### ISSUE THREAD

**Issue by bismitpanda** [shadcn-ui/ui#6920]
### Describe the bug

The new color changes made some of my custom themed UI to be extremely ugly. Some examples are attached below

Old:

![Image](https://github.com/user-attachments/assets/7f6825cc-25c8-468e-96e2-112be174a306)

![Image](https://github.com/user-attachments/assets/92c808d1-e380-483d-a477-470a8bf35f05)

New:

![Image](https://github.com/user-attachments/assets/61494f39-62f3-4370-9b08-aca9d8b723cd)

![Image](https://github.com/user-attachments/assets/b3571177-ed4a-4976-a647-23d866d83069)

### Affected component/components

Button

### How to reproduce

Use this stylesheet

```css
@import "tailwindcss";
@plugin 'tailwindcss-animate';
@custom-variant dark (&:is(.dark *));

@import "uploadthing/tw/v4";
@source "../../node_modules/@uploadthing/react/dist";

@theme {
  --font-sans:
    var(--font-outfit), ui-sans-serif, system-ui, sans-serif,
    "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";

  --font-mono:
    var(--font-space-mono), ui-monospace, Menlo, Monaco, "Segoe UI Mono",
    "Oxygen Mono", "Ubuntu Mono", "Source Code Pro", "Fira Mono",
    "Droid Sans Mono", "Consolas", "Courier New", monospace;
}

@layer base {
  *,
  ::after,
  ::before,
  ::backdrop,
  ::file-selector-button {
    border-color: var(--color-gray-200, currentColor);
  }
}

:root {
  --background: oklch(0.98 0 0);
  --foreground: oklch(0.2 0.05 155);
  --card: oklch(0.99 0 0);
  --card-foreground: oklch(0.2 0.05 155);
  --popover: oklch(0.99 0 0);
  --popover-foreground: oklch(0.2 0.05 155);
  --primary: oklch(0.45 0.18 145);
  --primary-foreground: oklch(0.99 0 0);
  --secondary: oklch(0.65 0.22 60);
  --secondary-foreground: oklch(0.15 0.03 255.5);
  --accent: oklch(0.92 0.05 230);
  --accent-foreground: oklch(0.15 0.03 255.5);
  --muted: oklch(0.8 0.03 155);
  --muted-foreground: oklch(0.5 0.05 155);
  --destructive: oklch(0.65 0.25 30);
  --destructive-foreground: oklch(0.99 0 0);
  --border: oklch(0.85 0.03 155);
  --input: oklch(0.85 0.03 155);
  --ring: oklch(0.55 0.12 145);
  --chart-1: oklch(0.45 0.18 145);
  --chart-2: oklch(0.65 0.22 60);
  --chart-3: oklch(0.7 0.15 230);
  --chart-4: oklch(0.5 0.12 130);
  --chart-5: oklch(0.7 0.15 80);
  --radius: 0.25rem;
  --sidebar: oklch(0.35 0.15 145);
  --sidebar-foreground: oklch(0.98 0 0);
  --sidebar-primary: oklch(0.55 0.15 145);
  --sidebar-primary-foreground: oklch(0.99 0 0);
  --sidebar-accent: oklch(0.65 0.22 60);
  --sidebar-accent-foreground: oklch(0.15 0.03 155);
  --sidebar-border: oklch(0.45 0.1 145);
  --sidebar-ring: oklch(0.55 0.15 145);
}

.dark {
  --background: oklch(0.15 0.04 155);
  --foreground: oklch(0.95 0 0);
  --card: oklch(0.18 0.05 150);
  --card-foreground: oklch(0.95 0 0);
  --popover: oklch(0.18 0.05 150);
  --popover-foreground: oklch(0.95 0 0);
  --primary: oklch(0.55 0.22 145);
  --primary-foreground: oklch(0.15 0.03 155);
  --secondary: oklch(0.7 0.25 60);
  --secondary-foreground: oklch(0.15 0.02 0);
  --accent: oklch(0.65 0.2 230);
  --accent-foreground: oklch(0.15 0.02 0);
  --muted: oklch(0.3 0.07 155);
  --muted-foreground: oklch(0.7 0.05 155);
  --destructive: oklch(0.7 0.28 30);
  --destructive-foreground: oklch(0.15 0.02 0);
  --border: oklch(0.3 0.07 155);
  --input: oklch(0.3 0.07 155);
  --ring: oklch(0.5 0.15 145);
  --chart-1: oklch(0.55 0.22 145);
  --chart-2: oklch(0.7 0.25 60);
  --chart-3: oklch(0.92 0.05 230);
  --chart-4: oklch(0.6 0.18 130);
  --chart-5: oklch(0.75 0.2 80);
  --sidebar: oklch(0.12 0.03 155);
  --sidebar-foreground: oklch(0.95 0 0);
  --sidebar-primary: oklch(0.55 0.22 145);
  --sidebar-primary-foreground: oklch(0.12 0.02 155);
  --sidebar-accent: oklch(0.7 0.25 60);
  --sidebar-accent-foreground: oklch(0.15 0.02 0);
  --sidebar-border: oklch(0.25 0.05 155);
  --sidebar-ring: oklch(0.5 0.15 145);
}

@theme inline {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
  --color-card: var(--card);
  --color-card-foreground: var(--card-foreground);
  --color-popover: var(--popover);
  --color-popover-foreground: var(--popover-foreground);
  --color-primary: var(--primary);
  --color-primary-foreground: var(--primary-foreground);
  --color-secondary: var(--secondary);
  --color-secondary-foreground: var(--secondary-foreground);
  --color-muted: var(--muted);
  --color-muted-foreground: var(--muted-foreground);
  --color-accent: var(--accent);
  --color-accent-foreground: var(--accent-foreground);
  --color-destructive: var(--destructive);
  --color-destructive-foreground: var(--destructive-foreground);
  --color-border: var(--border);
  --color-input: var(--input);
  --color-ring: var(--ring);
  --color-chart-1: var(--chart-1);
  --color-chart-2: var(--chart-2);
  --color-chart-3: var(--chart-3);
  --color-chart-4: var(--chart-4);
  --color-chart-5: var(--chart-5);
  --radius-sm: 0.125rem;
  --radius-md: 0.1875rem;
  --radius-lg: 0.25rem;
  --radius-xl: 0.375rem;
  --color-sidebar: var(--sidebar);
  --color-sidebar-foreground: var(--sidebar-foreground);
  --color-sidebar-primary: var(--sidebar-primary);
  --color-sidebar-primary-foreground: var(--sidebar-primary-foreground);
  --color-sidebar-accent: var(--sidebar-accent);
  --color-sidebar-accent-foreground: var(--sidebar-accent-foreground);
  --color-sidebar-border: var(--sidebar-border);
  --color-sidebar-ring: var(--sidebar-ring);
  --animate-accordion-down: accordion-down 0.15s cubic-bezier(0.16, 1, 0.3, 1);
  --animate-accordion-up: accordion-up 0.15s cubic-bezier(0.16, 1, 0.3, 1);

  @keyframes accordion-down {
    from {
      height: 0;
    }
    to {
      height: var(--radix-accordion-content-height);
    }
  }

  @keyframes accordion-up {
    from {
      height: var(--radix-accordion-content-height);
    }
    to {
      height: 0;
    }
  }
}

@layer base {
  * {
    @apply border-border/80 outline-ring/30;
  }
  body {
    @apply bg-background text-foreground;
  }
}

@layer components {
  .card {
    @apply bg-card border-border/40 shadow-sm;
  }

  .btn,
  .button {
    @apply font-medium tracking-wide transition-all duration-150;
  }

  button,
  a[role="button"],
  select,
  .interactive {
    @apply shadow-sm transition-all duration-150 hover:shadow-none;
  }

  *:focus-visible {
    @apply ring-ring/40 ring-offset-background ring-2 ring-offset-1 outline-none;
  }
}

@layer base {
  * {
    @apply border-border outline-ring/50;
  }
  body {
    @apply bg-background text-foreground;
  }
}
```

### Logs

```bash

```

### System Info

```bash
Browser: Zen Browser (Firefox 136.0)
OS: Ubuntu 22.04 (GNOME background)
```

### Before submitting

- [x] I've made research efforts and searched the documentation
- [x] I've searched for existing issues
