### ISSUE TITLE
[bug]: Chart problem with css variable

### ISSUE THREAD

**Issue by hosein-mola** [shadcn-ui/ui#7076]
### Describe the bug

Thank you for your time, please fix this 😁
Chart **doesn't** accept ```OKLCH``` or even ```HSL```, Both result in black and white default chart.

**Update**: PR #7062 seems to try to fix same issue.

```css
   // tested with oklch and hsl
  --chart-1: hsl(173 58% 39%); 
  --chart-2: hsl(12 76% 61%);
  --chart-3: hsl(197 37% 24%);
  --chart-4: hsl(43 74% 66%);
  --chart-5: hsl(27 87% 67%);
  --color-mobile: oklch(
    0.9115893545851754 0.04278297688944959 258.94532126217916
  );
  --color-desktop: oklch(0.1726618705035971 0.2579710144927536 265.9);
  --radius: 0.5rem;
```
![Screenshot 2025-03-28 224345](https://github.com/user-attachments/assets/145edacc-e87a-4900-a81c-7e66f8dda012)

### Affected component/components

Chart

### How to reproduce

1. create new nextjs project
2. add shadcn to it 
3. add chart to project
4. no color is used and fallback to default black and white chart color

also theme generator doesn't seems work with new color space as it generates hsl

### Logs

```bash

```

### System Info

```bash
chrome 134
windows 11
```

### Before submitting

- [x] I've made research efforts and searched the documentation
- [x] I've searched for existing issues

**Comment by enricoroselino** [comment]
the work around is remove the hsl() from config and turn the HSL value from css into OKCLH (im using chat gpt for this)

```javascript
const chartConfig = {
    visitors: {
        label: "Visitors",
    },
    desktop: {
        label: "Desktop",
        color: "var(--chart-1)",
    },
    mobile: {
        label: "Mobile",
        color: "var(--chart-2)",
    },
} satisfies ChartConfig;
```

```css
@layer base {
    * {
        @apply border-border outline-ring/50;
    }

    body {
        @apply bg-background text-foreground;
    }

    :root {
        --background: oklch(1 0 0);
        --foreground: oklch(0.123 0.015 265);
        --card: oklch(1 0 0);
        --card-foreground: oklch(0.123 0.015 265);
        --popover: oklch(1 0 0);
        --popover-foreground: oklch(0.123 0.015 265);
        --primary: oklch(0.075 0.017 265);
        --primary-foreground: oklch(0.98 0.002 0);
        --secondary: oklch(0.962 0.01 265);
        --secondary-foreground: oklch(0.075 0.017 265);
        --muted: oklch(0.962 0.01 265);
        --muted-foreground: oklch(0.558 0.014 265);
        --accent: oklch(0.962 0.01 265);
        --accent-foreground: oklch(0.075 0.017 265);
        --destructive: oklch(0.683 0.233 29);
        --destructive-foreground: oklch(0.98 0.002 0);
        --border: oklch(0.9 0.015 265);
        --input: oklch(0.9 0.015 265);
        --ring: oklch(0.123 0.015 265);

        /* Chart colors */
        --chart-1: oklch(0.725 0.208 36);
        --chart-2: oklch(0.565 0.164 181);
        --chart-3: oklch(0.422 0.11 213);
        --chart-4: oklch(0.76 0.212 82);
        --chart-5: oklch(0.772 0.22 62);
    }

    .dark {
        --background: oklch(0.123 0.015 265);
        --foreground: oklch(0.98 0.002 0);
        --card: oklch(0.123 0.015 265);
        --card-foreground: oklch(0.98 0.002 0);
        --popover: oklch(0.123 0.015 265);
        --popover-foreground: oklch(0.98 0.002 0);
        --primary: oklch(0.98 0.002 0);
        --primary-foreground: oklch(0.075 0.017 265);
        --secondary: oklch(0.182 0.012 265);
        --secondary-foreground: oklch(0.98 0.002 0);
        --muted: oklch(0.182 0.012 265);
        --muted-foreground: oklch(0.659 0.02 265);
        --accent: oklch(0.182 0.012 265);
        --accent-foreground: oklch(0.98 0.002 0);
        --destructive: oklch(0.365 0.18 29);
        --destructive-foreground: oklch(0.98 0.002 0);
        --border: oklch(0.182 0.012 265);
        --input: oklch(0.182 0.012 265);
        --ring: oklch(0.84 0.012 265);

        --chart-1: oklch(0.6 0.24 265);
        --chart-2: oklch(0.5 0.21 145);
        --chart-3: oklch(0.7 0.25 80);
        --chart-4: oklch(0.75 0.23 305);
        --chart-5: oklch(0.72 0.24 25);
    }
}
```
